import type { ScoreBand } from "./quotesLibrary";
import type { VerdictType } from "./templates";

export type CourtSentence = {
  gavelLine: string;
  gavelLineZh: string;
  recital: string;
  recitalZh: string;
  ruling: string;
  rulingZh: string;
  admonition: string;
  admonitionZh: string;
};

export const COURT_VERDICT_TEMPLATES: Record<VerdictType, Record<ScoreBand, CourtSentence[]>> = {
  CONVICTED: {
    doomed: [
      {
        gavelLine: "The court has heard enough.",
        gavelLineZh: "本庭所闻，已足够。",
        recital: "What was offered as conviction arrived without ballast.",
        recitalZh: "其所谓决心，徒有声势，并无压舱之物。",
        ruling: "This motion is denied in the strongest possible terms.",
        rulingZh: "本庭从严驳回此项动议。",
        admonition: "Do not confuse desperation with resolve again.",
        admonitionZh: "往后切莫再以穷迫充作决心。",
      },
      {
        gavelLine: "Silence in the chamber.",
        gavelLineZh: "肃静，法庭无须更多喧哗。",
        recital: "The record reveals impulse disguised as necessity.",
        recitalZh: "卷宗所示，不过冲动假借必然之名。",
        ruling: "The petition fails before it reaches the merits.",
        rulingZh: "其请未及本旨，先已自败。",
        admonition: "Return only when your evidence outlasts your mood.",
        admonitionZh: "待证据长于情绪，再来叩庭。",
      },
    ],
    weak: [
      {
        gavelLine: "The bench is prepared to rule.",
        gavelLineZh: "本席已可裁示。",
        recital: "The claim bears shape, though not yet sufficient force.",
        recitalZh: "其说虽有轮廓，然支撑仍嫌薄弱。",
        ruling: "The motion is denied without prejudice to future review.",
        rulingZh: "本庭驳回此议，容后再审。",
        admonition: "Strengthen the record before asking fate to sign it.",
        admonitionZh: "先把卷宗补厚，再求命运落款。",
      },
      {
        gavelLine: "The chamber will note this carefully.",
        gavelLineZh: "此案，本庭谨慎记之。",
        recital: "Earnestness is visible; adequacy is not.",
        recitalZh: "诚意可见，充足尚不可见。",
        ruling: "This court declines to authorize the step today.",
        rulingZh: "本庭今日不予放行。",
        admonition: "A wish is not a record, and a record is all that counts.",
        admonitionZh: "愿望不是卷宗，卷宗才算数。",
      },
    ],
    mixed: [
      {
        gavelLine: "The court remains divided within itself.",
        gavelLineZh: "本庭之内，意见尚有交争。",
        recital: "There is substance here, but not enough calm around it.",
        recitalZh: "其间并非无据，只是周遭犹多躁气。",
        ruling: "The motion is withheld pending fuller deliberation.",
        rulingZh: "此议暂缓裁断，留待再议。",
        admonition: "Do not rush what has almost become credible.",
        admonitionZh: "几近可信之事，尤不可躁进。",
      },
      {
        gavelLine: "The court will not be hurried.",
        gavelLineZh: "本庭不受催迫。",
        recital: "The case resists dismissal, yet invites scrutiny.",
        recitalZh: "此案不至于立斥，亦远未可轻许。",
        ruling: "Judgment is reserved, not surrendered.",
        rulingZh: "本庭保留裁断，非谓默许。",
        admonition: "Let time interrogate what argument has spared.",
        admonitionZh: "留些时日，让时间盘问你未盘问之处。",
      },
    ],
    solid: [
      {
        gavelLine: "The court acknowledges a stronger record.",
        gavelLineZh: "本庭认此卷宗，较前已强。",
        recital: "Discipline, not merely desire, has entered the file.",
        recitalZh: "入卷者不独欲望，亦有克制与秩序。",
        ruling: "The court still withholds full relief, but only narrowly.",
        rulingZh: "本庭仍暂不全然放行，然其距放行已不远。",
        admonition: "Guard this seriousness; it is your best witness.",
        admonitionZh: "守住这份郑重，它是你最好的证人。",
      },
      {
        gavelLine: "This bench does not dismiss what it can respect.",
        gavelLineZh: "本席对可敬之案，不轻易逐退。",
        recital: "The petitioner has answered more than was expected.",
        recitalZh: "其所答，已多于众人所料。",
        ruling: "The motion is denied for now, but not in spirit.",
        rulingZh: "此议今虽未准，其势已近可准。",
        admonition: "One more layer of proof may turn caution into leave.",
        admonitionZh: "再补一层证据，谨慎便可化为放行。",
      },
    ],
    resolute: [
      {
        gavelLine: "Even this court must concede the record.",
        gavelLineZh: "纵本庭严审，亦不得不认其卷。",
        recital: "Though the filing is formidable, the doubt has not vanished.",
        recitalZh: "虽卷宗可畏，疑虑终未尽除。",
        ruling: "The court denies immediate release, but with visible restraint.",
        rulingZh: "本庭仍不即刻放行，然此拒已带克制。",
        admonition: "What stands this tall must not lean on vanity now.",
        admonitionZh: "既已立得如此之高，便不可再倚虚荣。",
      },
      {
        gavelLine: "The bench resists, though not without respect.",
        gavelLineZh: "本席虽仍持保留，然已生敬意。",
        recital: "This is no reckless petition; it is merely one step shy of leave.",
        recitalZh: "此议并非妄动，只是尚差最后一纸通行。",
        ruling: "The court withholds final clearance by the narrowest margin.",
        rulingZh: "本庭以最窄之幅，暂缓最终放行。",
        admonition: "Finish the proof and the gate will open by law, not favor.",
        admonitionZh: "把最后一页证据补齐，门会依法而开，不靠恩准。",
      },
    ],
  },
  UNRESOLVED: {
    doomed: [
      {
        gavelLine: "The court declines certainty.",
        gavelLineZh: "本庭拒绝仓促的确定。",
        recital: "The chamber has heard more alarm than proof.",
        recitalZh: "满庭所闻，警报多于证据。",
        ruling: "This matter remains withheld in grave doubt.",
        rulingZh: "此案疑云甚重，暂不决断。",
        admonition: "Sleep before you sign what panic has drafted.",
        admonitionZh: "先去睡一觉，再签慌乱替你写的东西。",
      },
      {
        gavelLine: "No final word will be issued tonight.",
        gavelLineZh: "今夜，本庭不落终语。",
        recital: "The file trembles under its own contradictions.",
        recitalZh: "卷宗自相抵牾，纸页之间已有摇晃。",
        ruling: "Verdict is withheld until coherence enters the case.",
        rulingZh: "待其自洽，再议其可否。",
        admonition: "An undecided record is safer than a false certainty.",
        admonitionZh: "未决的卷宗，总比伪装的确定更安全。",
      },
    ],
    weak: [
      {
        gavelLine: "The court records hesitation without contempt.",
        gavelLineZh: "本庭记其迟疑，而不轻侮之。",
        recital: "There is a case here, though not yet one fit to close.",
        recitalZh: "此间确有一案，然未足以结庭。",
        ruling: "Final judgment is withheld at this stage.",
        rulingZh: "现阶段，本庭保留终判。",
        admonition: "Let the next evidence be quieter and better built.",
        admonitionZh: "下一份证据，最好更安静，也更牢。",
      },
      {
        gavelLine: "The bench will not force a verdict from fog.",
        gavelLineZh: "雾气未散，本席不逼作裁。",
        recital: "Earnest argument has arrived, but not yet enough clarity.",
        recitalZh: "陈词已有诚意，明度仍嫌不足。",
        ruling: "This court reserves judgment without dismissal.",
        rulingZh: "本庭留判，不等于逐回。",
        admonition: "Do not mistake delay for defeat; it may be mercy.",
        admonitionZh: "缓判未必是败，它也可能是宽宥。",
      },
    ],
    mixed: [
      {
        gavelLine: "The court hears both thunder and timber.",
        gavelLineZh: "本庭既闻雷声，亦闻木骨。",
        recital: "The petition contains danger and design in equal measure.",
        recitalZh: "此议险意与架构并存，难偏其一。",
        ruling: "The verdict is withheld pending one more season of truth.",
        rulingZh: "本庭暂留其判，待再经一季真相。",
        admonition: "What survives another season deserves a stronger bench.",
        admonitionZh: "能再熬过一季的，才配更坚定的法槌。",
      },
      {
        gavelLine: "The chamber refuses a hurried ending.",
        gavelLineZh: "本庭拒绝仓皇收场。",
        recital: "The record carries both risk and unusual promise.",
        recitalZh: "卷宗之中，风险与异样的希望并举。",
        ruling: "Judgment remains suspended above the case.",
        rulingZh: "此案之上，判决暂时悬而未落。",
        admonition: "Stay with the question until it stops flattering you.",
        admonitionZh: "把问题留在身边，直到它不再取悦你。",
      },
    ],
    solid: [
      {
        gavelLine: "The court is nearly persuaded.",
        gavelLineZh: "本庭几近为之所动。",
        recital: "The record carries unusual steadiness under pressure.",
        recitalZh: "此卷在重压之下，竟有少见的稳态。",
        ruling: "Verdict is withheld only to honor the gravity of release.",
        rulingZh: "本庭暂不落判，只为不轻薄放行之重。",
        admonition: "Keep the discipline that brought you this close.",
        admonitionZh: "守住把你送到这里的那份克制。",
      },
      {
        gavelLine: "The bench sees a path worth taking seriously.",
        gavelLineZh: "本席已见其路，且值得正视。",
        recital: "The argument no longer sounds like wish alone.",
        recitalZh: "其辩已不止于愿，亦颇见证据。",
        ruling: "Final leave is delayed, though respect is already granted.",
        rulingZh: "通行暂缓，敬意先至。",
        admonition: "A delayed blessing may still be a blessing.", 
        admonitionZh: "迟来的放行，未必不是放行。",
      },
    ],
    resolute: [
      {
        gavelLine: "The chamber stands at the edge of release.",
        gavelLineZh: "本庭已立于放行之边。",
        recital: "This case is stronger than many that came seeking certainty.",
        recitalZh: "此案之强，已胜许多求判之卷。",
        ruling: "The verdict is withheld by form, not by distrust.",
        rulingZh: "此番留判，出于程序，不出于不信。",
        admonition: "What is nearly free must still bear its final witness.",
        admonitionZh: "将近自由之物，仍须受最后一证。",
      },
      {
        gavelLine: "The bench would be reckless to sneer at this record.",
        gavelLineZh: "若轻慢此卷，反是本席轻率。",
        recital: "The petitioner has brought seriousness into full view.",
        recitalZh: "其人之郑重，已尽呈于庭前。",
        ruling: "Judgment is reserved only to preserve its dignity.",
        rulingZh: "保留裁断，只为留住裁断本身的分量。",
        admonition: "Stand still one moment longer; the door is already moving.",
        admonitionZh: "再稳住片刻，那扇门其实已经在动。",
      },
    ],
  },
  ACQUITTED: {
    doomed: [
      {
        gavelLine: "Against expectation, the record survives.",
        gavelLineZh: "出人意料，此卷竟未自毁。",
        recital: "What looked reckless was answered with uncommon substance.",
        recitalZh: "初看似鲁莽之举，竟被实据一一托住。",
        ruling: "The court grants leave despite its initial suspicion.",
        rulingZh: "本庭虽曾疑之，终予放行。",
        admonition: "Do not squander the mercy earned by proof.",
        admonitionZh: "既凭证据得免，切莫辜负这份宽准。",
      },
      {
        gavelLine: "The court revises its first instinct.",
        gavelLineZh: "本庭收回最初之疑。",
        recital: "The file entered weak and leaves strangely intact.",
        recitalZh: "此卷入庭时颇显单薄，出庭时反得其整。",
        ruling: "The motion is granted, narrowly but genuinely.",
        rulingZh: "此议准许，虽险而真。",
        admonition: "A narrow release still demands a careful gait.",
        admonitionZh: "险中得放，也须步步自持。",
      },
    ],
    weak: [
      {
        gavelLine: "The bench has reached its determination.",
        gavelLineZh: "本席已得其裁。",
        recital: "Though imperfect, the record bears enough weight to proceed.",
        recitalZh: "其卷虽不尽圆满，已足担其一程。",
        ruling: "The court grants this motion with measured confidence.",
        rulingZh: "本庭衡而后准，信之而不纵之。",
        admonition: "Proceed with gravity; permission is not immunity.",
        admonitionZh: "得准不等于免罪，放行仍须慎行。",
      },
      {
        gavelLine: "The chamber will not deny what has substance.",
        gavelLineZh: "有其实者，本庭不轻拒之。",
        recital: "The petition still shows seams, but none fatal.",
        recitalZh: "此议尚见缝隙，然无一处致命。",
        ruling: "Leave is granted and entered into the record.",
        rulingZh: "本庭准其所请，着录在卷。",
        admonition: "Do not let approval make you careless.", 
        admonitionZh: "切莫因获准而生轻忽。",
      },
    ],
    mixed: [
      {
        gavelLine: "The court is prepared to release this path.",
        gavelLineZh: "本庭可以放此一路。",
        recital: "The case contains enough truth to outrun its noise.",
        recitalZh: "其卷中真意，已足压过杂音。",
        ruling: "The motion is granted under the dignity of doubt answered.",
        rulingZh: "此议准许，因疑已得答。",
        admonition: "Let what convinced this court continue to govern you.",
        admonitionZh: "使本庭信服之处，亦当继续约束你。",
      },
      {
        gavelLine: "The bench finds the record mature enough to move.",
        gavelLineZh: "本席认此卷已成熟到可以起行。",
        recital: "The argument remains human, but no longer fragile.",
        recitalZh: "其辩仍带人味，却已不再脆弱。",
        ruling: "This court grants leave and expects you to carry it well.",
        rulingZh: "本庭准其所请，并望其善自承之。",
        admonition: "A granted path is still a path to be walked.", 
        admonitionZh: "被准许的路，终究还是要你自己走。",
      },
    ],
    solid: [
      {
        gavelLine: "The court sees no honorable reason to delay.",
        gavelLineZh: "本庭已无正当理由再拖延。",
        recital: "The petitioner has met challenge with evidence, not theater.",
        recitalZh: "其人所答，以证据为先，而不以表演取胜。",
        ruling: "The motion is granted and the record stands in good order.",
        rulingZh: "本庭准其动议，卷宗立而有序。",
        admonition: "Go with the sobriety that earned this release.",
        admonitionZh: "带着赢来此准许的克制，继续往前。",
      },
      {
        gavelLine: "This bench is satisfied.",
        gavelLineZh: "本席对此，已可称满意。",
        recital: "The file holds under pressure and answers with coherence.",
        recitalZh: "其卷受压而不散，应答之间亦见自洽。",
        ruling: "The court grants full leave to proceed.",
        rulingZh: "本庭正式准予放行。",
        admonition: "Now let action remain worthy of argument.", 
        admonitionZh: "此后所行，勿负此前所辩。",
      },
    ],
    resolute: [
      {
        gavelLine: "The court has heard enough to open the gate.",
        gavelLineZh: "本庭所闻，已足启门。",
        recital: "This record carries seriousness, evidence, and the discipline of consequence.",
        recitalZh: "此卷兼具郑重、证据，与承受后果之准备。",
        ruling: "The motion is granted in full and with dignity.",
        rulingZh: "本庭庄严放行，全数准许。",
        admonition: "Proceed, and let history meet you standing.", 
        admonitionZh: "去吧，让历史见你立着相迎。",
      },
      {
        gavelLine: "Let the chamber rise for the ruling.",
        gavelLineZh: "请全庭肃立，听取裁示。",
        recital: "The petitioner has answered challenge after challenge without collapse.",
        recitalZh: "其人历受盘问而不坠，其志已可验明。",
        ruling: "This court releases you to your chosen road.",
        rulingZh: "本庭放行——去走你所选之路。",
        admonition: "Walk carefully, but do not walk backward again.", 
        admonitionZh: "步子可以稳，方向不必再退。",
      },
    ],
  },
};
